### PR TITLE
Release FX Devices v1.0beta

### PR DESCRIPTION
**Pull request by BryanChi**

### CODE REVIEW

**Comment by BryanChi** [comment]
Shoot, I'm so sorry, I forgot to include the 'cookdsp' library that's required for the script to work. Is it possible to add it later on? They're all jsfx-inc files.

**Comment by cfillion** [comment]
Are all the files in the screenshot below needed & to be installed under `<resource path>/Effects/ReaTeam Scripts/BrianChi_FX Devices`? I can add them for you, will be quicker than remaking the entire PR.

Screen Shot 2023-01-03 at 08 03 43

**Comment by BryanChi** [comment]
Yes it's identical on my system so I believe so. Thank you again for helping me cfillion!!

**Comment by cfillion** [comment]
Added cookdsp, renamed bryanchi to BryanChi, and added this line to update the font path:
```diff
     local script_folder = select(2, r.get_action_context()):match('^(.+)[\\//]')
+    script_folder = script_folder .. '/BryanChi_FX Devices'
     FontAwesome = r.ImGui_CreateFont(script_folder .. '/IconFont1.ttf', 30)
```

Here's a temporary index link you can import to test the package before releasing:

```
https://github.com/ReaTeam/ReaScripts/raw/fx-devices-test/index.xml
```
It opens successfully without errors here, but I didn't check any further.

**Comment by BryanChi** [comment]
Thanks again for fixing the things I missed.
I did noticed and fixed a couple of things after uploading yesterday, I've edited it directly on Github if that's ok.

**Comment by cfillion** [comment]
> I did noticed and fixed a couple of things after uploading yesterday, I've edited it directly on Github if that's ok.

Yes, that's perfectly fine. All good on my end, is this ready for release now?

**Comment by BryanChi** [comment]
My bad! I was suppose to change the main script instead of the jsfxs. Things should work normally now.  Let me just quickly check after it's approved..

**Comment by BryanChi** [comment]
ahh! So sorry about the font path!

**Comment by cfillion** [comment]
I've updated the temporary index.xml above to test with the latest changes. Let me know if it's good to go!

**Comment by BryanChi** [comment]
Yes it all seems to be fine, I think it's ready!🎉🎉   Thank you again!!

**Pull request merged**
