### PR TITLE
Release Track-based split items (select left) v0.64

### PR DESCRIPTION
**Pull request by Triode123**

### CODE REVIEW

**Comment by cfillion** [comment]
It looks like you are releasing a bunch of closely related actions. If that is the case, I suggest bundling them in the same package so users may install/update them together.

**Comment by Triode123** [comment]
> It looks like you are releasing a bunch of closely related actions. If that is the case, I suggest bundling them in the same package so users may install/update them together.

Hi Christian

Thanks for that. 
I’m new to reapack uploads with github.
What’s the most straightforward way to do this?
Many thanks for your patience :)

Stef

**Comment by cfillion** [comment]
You already did it (perhaps accidentally?) in the first two PRs (#633 and #634). Set the package file's resource type to "Don't install", add all the action files and set them to be added to the Main action list section.

**Comment by Triode123** [comment]
> You already did it (perhaps accidentally?) in the first two PRs (#633 and #634). Set the package file's resource type to "Don't install", add all the action files and set them to be added to the Main action list section.

I uploaded all these scripts via the reapack upload page rather than directly on Github.  I'm afraid I can't see where to set the resource type or add the action files.   Can you give me some more pointers? 
Apologies!

**Comment by cfillion** [comment]
There is a "Resource type" dropdown menu in the "Provided files" section of the upload page. Select the package file and set it to "Don't install". Screenshot: https://i.postimg.cc/761drnM5/2021-02-17-1613592138.png

Click on the "Add file" button to insert a hosted file (or drag/drop it into the page). For each hosted files, select it in the left list and choose the desired action list sections in the "Action list" dropdown menu. Screenshot: https://i.postimg.cc/qqkYJ6jj/2021-02-17-1613592178.png

**Comment by Triode123** [comment]
Hi Christian

I’ve just re-uploaded after tidying up.  

Here’s a screenshot of how it looked before I hit upload this time
https://imgur.com/dumFsrQ <https://imgur.com/dumFsrQ>
Is this now correct?

Many thanks

Stef

**Pull request closed without merging**
