### PR TITLE
Release Scroll last touched track FX envelope into view v1.01

### PR DESCRIPTION
**Pull request by Edgemeal**

### CODE REVIEW

**Comment by Edgemeal** [comment]
Any idea why this error happens?

Add a track fx param envelope using this script, don't add any points to the envelope, press the envelope panel bypass button so that REAPER hides the envelope (as expected), now call the script again and it errors,... BR_EnvAlloc' argument 1: expected TrackEnvelope* , but env is not nil (and still same userdata ), how can it not be valid?

**Comment by cfillion** [comment]
What does `reaper.ValidatePtr(env, 'TrackEnvelope*')` returns?

**Comment by Edgemeal** [comment]
false :(

**Comment by Edgemeal** [comment]
I think I have it fixed, instead of checking env variable I used ValidatePtr()

THANKS!

**Pull request merged**
