### PR TITLE
Release nail the track envelopes heights v1.0

### PR DESCRIPTION
**Pull request by bobobo-git**

### CODE REVIEW

**Comment by cfillion** [comment]
v7.0pre9's changelog has this:
>  Envelopes: allow setting envelope zoom preference to 0% of track height (so envelopes are not affected by vertical zoom)

Is this script still relevant? I tried in v7.0pre9, with default settings, blank project with three tracks & the first one having volume and pan envelopes. Ctrl (Cmd on macOS) + mousewhell resizes both tracks and envelopes. Running the script first does not prevent them from being resized along with the track.

**Comment by bobobo-git** [comment]
relevant?  yes, i think so.this script doesn't fix the envelops heights overall but set heights of actual existing when. (may be i should enhance the description a little in v1.1)if you change the height of one track (*) that has envelope and have run this script before the envelope will maintain its height.(*) dragging at the lower side of the track in tcp or use this sws/wol change height of track or envelope when hovered (midicc  mousewheel) f.i. i set  'shift cmd wheel' to ru n it.cmd wheel will reset the envelope heights to default (obeying the new zoom factor thing) best wishes :)Am 18.08.2023 01:49 schrieb Christian Fillion ***@***.***>:
v7.0pre9's changelog has this:

Envelopes: allow setting envelope zoom preference to 0% of track height (so envelopes are not affected by vertical zoom)

Is this script still relevant? I tried in v7.0pre9, with default settings, blank project with three tracks & the first one having volume and pan envelopes. Ctrl (Cmd on macOS) + mousewhell resizes both tracks and envelopes. Running the script first does not prevent them from being resized along with the track.

**Comment by bobobo-git** [comment]
ok, in 7.0pre9 the new
   # Envelopes: allow setting envelope zoom preference to 0% of track
height (so envelopes are not affected by vertical zoom)

MY SCRIPT HAS LOST IT'S RELEVANCE


though i hear everybody scream to have a fixed envelope height in px
when creating


Greetings from here :)


Am 18.08.2023 um 06:39 schrieb Bobobo vom Friesenknecht:

**Comment by bobobo-git** [comment]
has lost the relevance

**Pull request closed without merging**
