### PR TITLE
Release Save and restore selected tracks floating FX windows (4 slots) v1.03

### PR DESCRIPTION
**Pull request by Edgemeal**
Add support for Master track

### CODE REVIEW

**Comment by Edgemeal** [comment]
**Support FX in Container (REAPER v7.00)**

Not sure what I did (using ReaPack online tool) but in ReaPack the 'About' text shown above should be in the  "History" for v1.03. :/ Oh well not a big deal I guess?

**Comment by cfillion** [comment]
Removed the line. (Since `about` is a package-level tag, it's effective without having to bump the version number.)

**Comment by Edgemeal** [comment]
OK but, ReaPack History >>>
v1.03 by Edgemeal – October 18 2023
  Add support for Master track

Its suppoed to say,
v1.03 by Edgemeal – October 18 2023
Support FX in Container (REAPER v7.00)

**Comment by Edgemeal** [comment]
I ran ReaPack online upload tool to only update the Changelog info for v1.03, I hope that worked.  :)

**Pull request merged**
