### PR TITLE
Tons of script naming fixes

### PR DESCRIPTION
**Pull request by mkruselj**

### CODE REVIEW

**Comment by X-Raym** [comment]
@cfillion What do you think about this pull request ? It seems to only affect action description in Reapack browser so I don't think it breaks anything else. But the PR do have conflict now.

@mkruselj you were very motivated to correct all that ! ✌️

**Comment by mkruselj** [comment]
I was indeed quite motivated. :D

**Comment by X-Raym** [comment]
@cfillion what do we do about this ? Do you think it is relevant to fix these ?

**Comment by X-Raym** [comment]
@mkruselj Hi ! This is a very good PR, we should have accepted since a long time, but the repo has change quite a bit since then, and it is too difficult to merge directly. @cfillion will try to answer this pro grammatically so it also works for newly added scripts. He will take care of description tag so that it matches file names. If they are more subtle changes, then it may be lost, but it would requires too much time to invest. We also count on original scripts authors to fix their typos 😉

I close this cause it will be handle differently.

This was the last opened PR on any ReaTeam repo 😎

**Comment by mkruselj** [comment]
Sounds good!

**Pull request closed without merging**
