### PR TITLE
Release Tempo marker list v1.0

### PR DESCRIPTION
**Pull request by Hypexed**

### CODE REVIEW

**Comment by Buy-One** [comment]
>_Hi_
>
>_The extension is Lua, but the language seems to be EEL2_

**Comment by Hypexed** [comment]
It is EEL. Don't know why it's on Lua. All my local files are EEL. Something must have messed up in the package manager. The file name definitely would have eel on the end. :-?

**Comment by Hypexed** [comment]
This should be good to go now.

**Comment by cfillion** [comment]
Replaced by #1099.

**Pull request closed without merging**
