### PR TITLE
Update tompad_FX_chain_AB.lua to v1.01

### PR DESCRIPTION
**Pull request by tompad2**
Made some checks for selected track, if fx chain is present, if inject is done.
Made changes to the GUI also because it didnt look the same on Windows
as when developed on linux.

### CODE REVIEW

**Comment by cfillion** [comment]
Had to merge it manually because your fork's master branch diverges from upstream. In git, each pull requests should be made from a unique branch.

I also added the PR's text as v1.01's user-facing changelog.

If you're still having problems with the website's uploader, I'd need the exact error message to figure out what's wrong. There could be clues in your browser's console as well (right click -> inspect element -> console).

**Comment by tompad2** [comment]
_Had to merge it manually because your fork's master branch diverges from upstream. In git, each pull requests should be made from a unique branch._

Strange, I synced my forge before i pulled it. Have to admit I am not safe regarding handling github, sorry if I create troubles.
Should I choose "Create a new branch for this commit and start a pull request" instead of "Commit directly to the master branch" after making changes? 

_I also added the PR's text as v1.01's user-facing changelog._

...sorry, what is "PR's text as v1.01's user-facing changelog._"?

_If you're still having problems with the website's uploader, I'd need the exact error message to figure out what's wrong. There could be clues in your browser's console as well (right click -> inspect element -> console)._

I could only see "Error" - I was on a PC with Ubuntu(linux), could that interfere?? 
It did interfere with the look of my script on Windows ;-) hence the today update.

I will try again with ReaPacksite on my Windows computer next time I will make a change or upload a new script.

**Comment by cfillion** [comment]
> Should I choose "Create a new branch for this commit and start a pull request" instead of "Commit directly to the master branch" after making changes?

The former: "Create a new branch for this commit and start a pull request".

> what is "PR's text as v1.01's user-facing changelog._"?

https://github.com/ReaTeam/ReaScripts/blob/ed2d9bf954ab821cd79a5817290dde457d2d9a7d/FX/tompad_FX%20chain%20AB.lua#L4-L6

Screen Shot 2023-03-15 at 18 00 12

> I could only see "Error" - I was on a PC with Ubuntu(linux), could that interfere??

It's possible that web browser settings or extensions could have an effect. The website not displaying a proper error message leads me to think it's a bug of some kind. Hoping the browser's console has more information. A screenshot/licecap would be helpful as well.

EDIT: Something you could additionally try is deleting the fork (https://github.com/tompad2/ReaScripts) and let the website uploader re-create it.

**Comment by tompad2** [comment]
Ok, "Create a new branch for this commit and start a pull request" it will be!

I will test ReaPacksite again soon, I found a strange bug in my code:
When testing the script on my DAW(Win) it worked after some time
re-coding. But after it showed up in ReaPack and I tested it from there
it throw errors on me ;-(. When I fixed it I try ReaPacksite again and
if error shows up I take a screenshot. 

After that I delete the fork if it not works.

**Comment by tompad2** [comment]
OK - I tried ReaPacksite from my DAW(Win) with the same webbrowser (Firefox) and it worked!
No error message now.

**Pull request closed without merging**
