### PR TITLE
Release Mini song switcher v2.1

### PR DESCRIPTION
**Pull request by mschnell1**
Allow for accessing multiple project tabs
bug fixes

### CODE REVIEW

**Comment by mschnell1** [comment]
@cfillion 
Version 2 now features two eel files. 
Is there a problem with that ? 

This lin
```
 @provides [main] mschnell_Mini song switcher/New file 1.lua > mschnell_Mini song switcher/mschnell_Mini song switcher project.eel
```
seems weird to me. but it seems to  be automatically generated

Thanks !

**Comment by cfillion** [comment]
It shouldn't be named "New file 1.lua". (Guessing you've changed the "install filename" instead of the "storage filename")

**Comment by mschnell1** [comment]
@cfillion 
Will it work now ?

**Comment by mschnell1** [comment]
[remove duplicate header block](https://github.com/ReaTeam/ReaScripts/pull/1411/commits/89302b8598b83378f98047ee7fcc4053693e4c9d)

Thanks, but

Still does not seem to work....

**Comment by cfillion** [comment]
> Still does not seem to work....

It doesn't work? If there's a bug in the script I'll hold off merging this until it's fixed then...

**Comment by mschnell1** [comment]
> > Still does not seem to work....
> 
> It doesn't work? If there's a bug in the script I'll hold off merging this until it's fixed then...

I do suppose the scripts work. 

I meant pushing the v2.1 package to ReaPack did not work, even though I did get a "has been merged" message.

**Comment by cfillion** [comment]
> even though I did get a "has been merged" message.

I merged it now, it wasn't before.

**Comment by mschnell1** [comment]
@cfillion 
for some reason when I updated v1 -> v2 using the web tool, the new description was added to the old one instead of replacing it. 
You kindly tried to mend this by deleting one copy. 

Unfortunately the old copy (for v1) remained.

Is the  other text still available or should I re-edit the merged version using the upload tool ? 

Thanks !

**Comment by mschnell1** [comment]
@cfillion 
The second script 'mschnell_Mini song switcher project.eel' starts with a line `-- @noindex`, that somehow has been added by ReaPack.

Reaper cant compile that :( 

What can I  do about that ?

**Comment by cfillion** [comment]
Ah yeah, it was added by the web upload tool because the file was in .lua ("New file 1.lua"). It would have added `// @noindex` if the filename had ended in `.eel`. I've fixed it in #1412. Named it v2.1.1, good to go?

**Comment by mschnell1** [comment]
@cfillion 
Yep. should work...

**Pull request merged**
