### PR TITLE
Release Lyricator v1.0

### PR DESCRIPTION
**Pull request by DaveInDev**
1.0 : initial release

### CODE REVIEW

**Comment by X-Raym** [comment]
Note: This will probably be on its own repo. Will close at this point.

**Comment by DaveInDev** [comment]
yes I created my own repo.
https://raw.githubusercontent.com/DaveInDev/Binbinhfr-Scripts/master/index.xml

I just wonder how it can be added to the official Reapack release, without the need for users to import it manually ?

**Comment by X-Raym** [comment]
We prefer to let users add repos manually, built in repos are managed by reateam admins :P

**Comment by DaveInDev** [comment]
ok. But I do not understand : cfillion (who seems to be reapack author) and xraym are the same person ?  :-)

**Comment by X-Raym** [comment]
@DaveInDev we are different people. @cfillion is reapack creator, dev, owner. We both are admin of this repository.
This repository is good for people participating once occasionally with simple scripts because we do code review. It seems to be you were more in a hurry and needed quicker updates so I advice you to create your own repository, which for people making more scripts or script with fast update cycle is better.
We only included built in in reapack ReaTeam repos, mine and MPL one, who made this group. We communicate often and so far we didnt include other repos for various reasons, like letting the user be sure of what he install without overwhelming him/here with tons of repos out of the box, repos for which we didnt make code review and for which if there is any issue, reapack will be blame (users still have lot of confusion about what reapack is and how it is managed, so we keep things out of the box as simple as possible).

**Comment by DaveInDev** [comment]
ok thanks (merci, je suis aussi francais), all is clear now.

**Pull request closed without merging**
