### PR TITLE
BuyOne_Load FX chain on selected objects

### PR DESCRIPTION
**Pull request by Buy-One**

### CODE REVIEW

**Comment by cfillion** [comment]
It would be nice to have that guide in the about tag, so it can be viewed in both ReaPack and the IDE.

The script could even have "help" operation mode that opens its documentation:

```lua
function help()
  if not reaper.ReaPack_GetOwner then
    reaper.MB('This feature requires ReaPack v1.2 or newer.', scriptName, 0)
    return
  end

  local owner = reaper.ReaPack_GetOwner(({reaper.get_action_context()})[2])

  if not owner then
    reaper.MB(string.format(
      'This feature is unavailable because "%s" was not installed using ReaPack.',
      scriptName), scriptName, 0)
    return
  end

  reaper.ReaPack_AboutInstalledPackage(owner)
  reaper.ReaPack_FreeEntry(owner)
end
```

**Comment by Buy-One** [comment]
Where can the Help be seen in action, can you recommend some scripts which use it?

**Comment by cfillion** [comment]
Double click in the package browser (or right click > About this package).

Most of juliansader's scripts have extensive documentation. My "Show all saved nudge settings", "Song switcher" and "Interactive ReaScript" scripts use the function above to open it from their gfx UI via a "?" button/context menu.

**Comment by Buy-One** [comment]
Please check if it's properly formatted. I've noticed that Julian's scripts don't include ReaPack tags and yet the info from the comments is displayed within the application. How is this achieved?

E.g.
https://github.com/ReaTeam/ReaScripts/blob/master/MIDI%20Editor/js_Move%20all%20selected%20events%20in%20active%20take%20together%20with%20mouse.lua

https://github.com/ReaTeam/ReaScripts/blob/master/MIDI%20Editor/js_Notation%20-%20Set%20beaming%20of%20selected%20notes%20to%20custom%20rhythm.lua

https://github.com/ReaTeam/ReaScripts/blob/master/MIDI%20Inline%20Editor/js_Select%20CC%20lanes%20to%20show%20in%20selected%20MIDI%20items.lua

**Comment by cfillion** [comment]
Fixed the formatting. I recommend using https://reapack.com/upload for generating and previewing it (and optionally submitting the PR).

>  I've noticed that Julian's scripts don't include ReaPack tags and yet the info from the comments is displayed within the application. How is this achieved?

reapack-index support both `@tagname value` and `tagname: value` syntaxes. 'ReaScript Name' is an alias for 'description'. He's also using a now-deprecated changelog syntax.

**Comment by Buy-One** [comment]
Thank you. I reformatted it to look like Julian's which i prefer more. I also prefer it to have the "guide inside" appendage, because after installation the user interacts with the script in the Action list and that will serve as a reminder or a pointer.

**Pull request merged**
