### PR TITLE
Release Live Keys Scripts v1.0

### PR DESCRIPTION
**Pull request by larryseyer**

### CODE REVIEW

**Comment by cfillion** [comment]
I pushed several changes:

- Renamed all "New file X.lua" files to proper names
- Marked the action files for registration in the Action List
- Moved the main code from "New file 19.lua" into the package file
- Merged the different "Track X" into a single source file (action.lua), using the filename to detect which track it is at runtime (see https://github.com/cfillion/reapack-index/wiki/Examples#multiple-slots)
- Renamed files to contain author prefix + sentence case name: "larrysayer_Live keys scripts - Track X.lua"
- Removed non-ReaPack installation instructions from the about text

**Comment by larryseyer** [comment]
Thank you.

However, my name is spelled Seyer (not Sayer)... so we need to change any edits to be spelled larryseyer_xxx_ETC.

I'm not sure how to do this since this is my first one...

Any help would be greatly appreciated.

Lastly, is there anything I need to do such as agree or commit?  As I said, I'm a nube with this.

Larry

**Comment by cfillion** [comment]
> However, my name is spelled Seyer (not Sayer)... so we need to change any edits to be spelled larryseyer_xxx_ETC.

Oops, typo in my message. The actual action names are written as "larryseyer". You can review the current version of the pull request here on the "Files changed" tab (https://github.com/ReaTeam/ReaScripts/pull/733/files).

> Lastly, is there anything I need to do such as agree or commit?

 If you're fine with the current state (eg. the renamed action names), I'll release this right away.

**Comment by larryseyer** [comment]
I'm fine with it.  Thank you for your help.

I like the 'parse the file for the track number' idea... makes for smaller code.  Good one!

Publish it!

**Pull request merged**
