### PR TITLE
Release Restore tracks floating fx windows (4 slots) v1.02

### PR DESCRIPTION
**Pull request by Edgemeal**
Add support for Master track

### CODE REVIEW

**Comment by cfillion** [comment]
Sorry, somehow I missed it when reviewing the initial release in 2020, but scripts that are meant to be exclusively used together should be packaged together. For example "Save and restore selected tracks floating FX windows (4 slots)". Otherwise users can find & install only one of them and be confused. (Or even update one but not the other and get bugs.)

**Comment by Edgemeal** [comment]
I had a hard enough time making script work for 4 slots LOL, no clue what I'm supposed to do to make both of those into one package now! :(

**Comment by cfillion** [comment]
No worries, made it for you in #1117 and recorded it for future reference.

Take

**Comment by Edgemeal** [comment]
> No worries, made it for you in #1117 and recorded it for future reference.
Many, many thanks!

**Pull request closed without merging**
