### PR TITLE
Release ReaChorder v2.0

### PR DESCRIPTION
**Pull request by flaneurette**

### CODE REVIEW

**Comment by cfillion** [comment]
Here's an index.xml of this PR for testing, which can be imported in ReaPack: http://sprunge.us/06ozRe.

> Your SWS version (< 2.12) is not supported. Please visit: https://www.sws-extension.org/ and update SWS.

^ This shows up with a (yet unreleased) 2.13 SWS build.

> Could not import rs_statemanager.  
> Could not import reaChord_data.  
> Could not import rs_midi.  
> Could not import reaper_track.  
> Could not import sections.  

The ReaChorder directory (which I'll rename to Flaneurette_ReaChorder before release, to match this repository's naming convention) is not present in `sys.path`. Adding this line solves it:

```py
sys.path.append('./ReaChorder')
```

After fixing the above, this shows up:

> ```
> Traceback (most recent call last):  
>   File "ReaChorder.py", line 141, in <module>  
>     class ReaChord(RSStateManager):  
> NameError: name 'RSStateManager' is not defined
> ```

Also it just crashes REAPER on macOS, should this also be Linux+Windows only?

```
Thread 0 Crashed:: reaper  Dispatch queue: com.apple.main-thread
0   libpython3.9.dylib            	0x000000012536269b do_warn + 362
1   libpython3.9.dylib            	0x0000000125362509 warn_unicode + 32
2   libpython3.9.dylib            	0x00000001253624c1 _PyErr_WarnFormatV + 56
3   libpython3.9.dylib            	0x000000012536483c PyErr_ResourceWarning + 136
4   libpython3.9.dylib            	0x00000001254718df fileio_dealloc_warn + 116
5   libpython3.9.dylib            	0x00000001252b7d0b method_vectorcall_O + 101
6   libpython3.9.dylib            	0x00000001252ad77e PyObject_VectorcallMethod + 136
7   libpython3.9.dylib            	0x00000001254756fa buffered_dealloc_warn + 81
8   libpython3.9.dylib            	0x00000001252b7d0b method_vectorcall_O + 101
9   libpython3.9.dylib            	0x00000001252ad77e PyObject_VectorcallMethod + 136
10  libpython3.9.dylib            	0x000000012547f97d _io_TextIOWrapper_close + 210
11  libpython3.9.dylib            	0x00000001252b7e05 method_vectorcall_NOARGS + 99
12  libpython3.9.dylib            	0x00000001252ad77e PyObject_VectorcallMethod + 136
13  libpython3.9.dylib            	0x000000012546debc iobase_finalize + 385
14  libpython3.9.dylib            	0x000000012541e275 collect + 2815
15  libpython3.9.dylib            	0x000000012541eb97 _PyGC_CollectNoFail + 56
16  libpython3.9.dylib            	0x00000001253f7339 finalize_interp_clear + 53
17  libpython3.9.dylib            	0x00000001253fa3bd Py_EndInterpreter + 116
18  com.cockos.reaper             	0x00000001073eb6cd PythonAPI::InterpretScript(char const*, char const*) + 1517
19  com.cockos.reaper             	0x00000001074590dc RunReaScript(char const*, int, KbdSectionInfo*, int, bool, int) + 1548
```

**Comment by flaneurette** [comment]
Yes, on Mac it is problematic so need to list it as Windows and Linux but cannot seem to checkbox both on ReaPack.

**Comment by cfillion** [comment]
The main package file must be directly in the MIDI Editor directory to not add an extra category. I'll push a commit shortly to fix the missing author prefix and set to Linux+Windows only. (Also my previous suggestion of `sys.path.append('./ReaChorder')` was wrong, it should have been `sys.path.append(sys.path[0] + '/ReaChorder')`).

> Can I simply upload ReaChorder.py through the ReaPack website?

Before release it the PR can be only be edited (without re-uploading everything) using regular git/GitHub means, as you've done above.

> Yes, on Mac it is problematic so need to list it as Windows and Linux but cannot seem to checkbox both on ReaPack.

It can be done using the editor GUI but it's a bit repetitive when many files are involved. I'll do that change manually with a quick search/replace regex.

**Comment by cfillion** [comment]
reaChord_Data.py was missing, so I grabbed it from [the repository](https://github.com/flaneurette/ReaChorder/blob/master/reaChord_data.py). Should be good now!

Here's a new index for testing: http://sprunge.us/Z82pGH.

Works!

**Comment by flaneurette** [comment]
I did add the following line:

> try:
>     ->import rs_statemanager
>     from rs_statemanager import RSStateManager

Perhaps, some versions of Python needs explicit named import before calling it, but I am not sure. 

The Tk screenshot, yes that happens when relaunching ReaChorder when testing, should be no issue when restarting Reaper.

**Comment by cfillion** [comment]
Added the line. Is this good to release now on your end?

**Comment by flaneurette** [comment]
Yes. I will test it as well in ReaPack, but it should work now.

**Pull request merged**
