### PR TITLE
Create BuyOne_Automatically increase height of selected tracks, decrease others'.lua

### PR DESCRIPTION
**Pull request by Buy-One**

### CODE REVIEW

**Comment by X-Raym** [comment]
@Buy-One The keyword "contract" isnt used for track height, maybe rename to something more common like "minimize", and add the "heigh" keywords in this so that it can be found when looking more easily.

**Comment by Buy-One** [comment]
@X-Raym Done

**Comment by X-Raym** [comment]
is the quote at the end of script name here intentional?
https://github.com/ReaTeam/ReaScripts/pull/1156/commits/103535f9cb0ee12e7f45a7262cdb5b9289853fb8#diff-7417b800340cf8e2b0b0e7cecf4f0fb559871bfe6f134e00277b05f9d97363e8R450

If yes then I guess it is ready to be merged

**Comment by Buy-One** [comment]
Yes it's possessive apostrophe, an abbreviation of `others' height`

**Comment by X-Raym** [comment]
@Buy-One Oh yes ok, it is not in any other action using "text, verb others" type of naming:
https://www.extremraym.com/cloud/reaper-action-list/?s=others

I encourage to stay to naming conventions, having this possessive apostrophe seems facultative and uncommon, so for consistency, it would be better without IMHO (despite being best english).

I hope you are not too bothered by these code reviews nipticks :S

**Comment by Buy-One** [comment]
The examples you linked to are different, in them **others** is an object, e.g. **minimize others**, **hide others**, the action is applied to **others** directly.
In this script name the object is the height, it's **others' height** which is decreased, not others themselves, in other words **decrease the height `of` others**. It's a facility to reduce redundancy.

I believe the apostrophe won't affect the name searchability, it will be ignored.

**Comment by X-Raym** [comment]
@Buy-One ok let's try his, could still be modified after the fact anyway

**Comment by Buy-One** [comment]
@X-Raym Thank you

**Pull request merged**
