### PR TITLE
Create BuyOne_Move selected FX envelope in track to top_bottom_upwards_downwards.lua

### PR DESCRIPTION
**Pull request by Buy-One**

### CODE REVIEW

**Comment by Edgemeal** [comment]
Isn't this package supposed to install four scripts? Only shows one listed in ReaPack contents, and when installed all I get is the main named one, but when copied and renamed manually for up/down actions they worked,.. so script seems OK, just the metadata stuff is messed up???

BTW... REAPER v6.52 & v6.53 on WIn10_x64

**Comment by cfillion** [comment]
Fixed in 2e529c133fc11ee475ff9785bcab376f8833c4b4.

**Comment by Buy-One** [comment]
@Edgemeal  Sorry about the hassle

@cfillion Thank you

**Comment by Edgemeal** [comment]
**@ Buy-One** Your scripts act a bit weird! I move a selected envelope up one place and it also moves the very top envelope to the bottom, and visa-versa for the move envelope down (the whole list of envelopes are moving up/down).
Is that the intended behavior?

FWIW, I mainly tried this script because a member asked for my scripts (fixed scripts by me2beats) that I posted a few years ago on forum (but recently deleted), so I sent him over to ReaPack.

**Comment by Buy-One** [comment]
@Edgemeal Yes it is, i'm preparing a new package version including instances which only swap 2 adjacent lanes leaving the rest intact.

**Pull request merged**
