### PR TITLE
Release Item stretch list in time selection v1.1

### PR DESCRIPTION
**Pull request by Hypexed**

### CODE REVIEW

**Comment by Buy-One** [comment]
Hi

https://github.com/Hypexed/Reaper-Scripts/raw/main/StretchList.png isn't available

**Comment by Hypexed** [comment]
This is Github making images complicated again. I was able to fix the other one. But I'm unable to edit this. Maybe need to cancel and redo again.

**Comment by Hypexed** [comment]
This should be good to go now.

**Comment by cfillion** [comment]
Replaced by #1098.

**Pull request closed without merging**
