### PR TITLE
Release MusiCollaboration v1.2.1

### PR DESCRIPTION
**Pull request by IvoDueblin**
I am totally new to Github and the corresponding processes. Apologies if I failed to upload my scripts correctly.

### CODE REVIEW

**Comment by X-Raym** [comment]
@IvoDueblin This script is just a pop up ? and why v 1.2.1 for first release ?

As it seems that this is a project of its own involving several future scripts, custom doc, I think it may worths that you have your own repository. You will be able to push update faster and have all your files in a separate repo. 😉

**Comment by IvoDueblin** [comment]
> 

Thanks for your reply, X-Raym. MuCol (MusiCollaboration) actually consists of 3 scripts - the script "MusiCollaboration.lua" is just a placeholder - the other 3 scripts are relevant. "MC_ToggleIndicator.lua" and "MC_ProcessProject.lua" call "MC_CollabControl.lua" with varying parameters, i.e. those 3 scripts need to be integrated into Reaper - the first two can be assigned to e.g. toolbar-buttons and you are good to go. Documentation and videos with all the details of how to install and use the scripts can be found at www.mucol.ch

**Comment by X-Raym** [comment]
@IvoDueblin arent the other lua files also meant to be used from action list ? In this case, you can register them directly without using placeholder.

IMHo this repo should be kept for common, general utility scripts, big 'projects' or very specific scripts are better on their own repo.
But I'll asi other members of reateam members about this.

thx for having considerate participing to this repo anyway !

**Comment by IvoDueblin** [comment]
Placeholder for Git only, not in Reaper. Yes in Reaper the 3 other scripts need to be included in the action list.
In principle I'm happy to follow your advice, create an new repository (once I find out how to do so :-) ) and add the scripts there. However, the initial idea to load the scripts into Git in the first place was, to may be participate more in the Reaper-ecosystem and hopefully get a chance to make MuCol known to a broader audience.

**Comment by X-Raym** [comment]
@IvoDueblin We can help you set up your repo if needed. It would IMHO good for your users to have things all with your branding :P But mostly it will allows you to do quick and fast updates without n eeding for PR etc as I suppose such projects do require quite some maintenance.

You can start by forking this : https://github.com/cfillion/reapack-repository-template

And then you can upload your file on it. If you didn't created the reapack header yourself, check file header here : https://github.com/ReaTeam/ReaScripts/pull/892/commits/5d0a78039e850a331c564a74488de600197b1c0b

It has auto reapack-index, but you can also do this locally with https://github.com/cfillion/reapack-index/wiki

Remember that the purpose of provides is more to link external resources to a script (like PNG files, data etc) or allows a script to generate several version (like playrate adjusted by 10%, 15%, 20% etc) in one package.
In your case, as each scripts has to be in main action, don't use the main placeholder script, and just put regular headers to the other one. It will be cleaner.

Let us know if you are stuck or when it is done,
I leave this PR open for now 

Good luck !

**Comment by X-Raym** [comment]
I close the PR as you delete the file :P
We stay open for assistance though ! Let us know how it goes !

**Pull request closed without merging**
