### PR TITLE
Release Mini Song Switcher v1.0

### PR DESCRIPTION
**Pull request by mschnell1**
Initial Release

### CODE REVIEW

**Comment by mschnell1** [comment]
@cfillion 
VS Code just informed me that no reviewer has been assigned to this merge request. 
How can I do this ?
Does the ReaTeam Contributing web interface not do this ? 
(In Fact with any commits I did (quite a lot) I seldom got any response before I sent a personal message to you.) Do I do something wrong ?

**Comment by mschnell1** [comment]
I found several typos in the description I'd like to correct. 
I understand I only can do modifications after the release.

**Comment by cfillion** [comment]
> VS Code just informed me that no reviewer has been assigned to this merge request.

We don't "assign reviewers" here.

> I found several typos in the description I'd like to correct.
> I understand I only can do modifications after the release.

You can push changes to your branch ([reapack.com_upload-1717010032085](https://github.com/mschnell1/ReaScripts/tree/reapack.com_upload-1717010032085)) before the PR is merged.

**Comment by mschnell1** [comment]
OOps. for some reason this is a lua file instead of an eel file
I somehow did something wrong when uploading it.
trying to resolve the problem....

**Comment by mschnell1** [comment]
I close this to prevent merging ....

**Comment by mschnell1** [comment]
I recreated the content as an eel file
I re-open this, hoping this is the correct way to have it merged....

**Comment by mschnell1** [comment]
seems like the checks passed....

**Comment by mschnell1** [comment]
I see I can git clone https://github.com/mschnell1/ReaScripts :) 
Does this mean I can use git (or in fact VSCode) do manage my ReaScript uploads  ? 
...
(in fact in the cloned folder, I do see my "old" contribution "mschnell_Mute Track X.eel", but not the (not yet released) ) "mschnell_Mini Song Switcher.eel" file I just created in the gihub web interface.)

**Comment by mschnell1** [comment]
I suppose this is OK now.

**Comment by mschnell1** [comment]
@cfillion 
Ooops. 

when train to git clone I get 

`error: unable to create file Regions/Mordi_Create single region from selected items (get name and color from folder track)/Mordi_Create single region from selected items (get name and color from folder track) and mark it in region render matrix via master.lua: Filename too long`

something weird in the repository ???

**Comment by mschnell1** [comment]
`git checkout -f` did work

**Comment by mschnell1** [comment]
I needed to update the file to v1.1, as markdown made italics from the `_song_` word in the description, making the script essentially unusable.

**Pull request merged**
