### PR TITLE
Release Tempo marker list in time selection v1.0

### PR DESCRIPTION
**Pull request by Hypexed**

### CODE REVIEW

**Comment by Buy-One** [comment]
Hi

The extension is Lua, but the language seems to be EEL2

**Comment by Hypexed** [comment]
Ok this should be fixed as well now.

**Comment by Buy-One** [comment]
@Hypexed

Also double hyphen used to comment out the header tags will produce error in EEL2

**Comment by Hypexed** [comment]
@Buy-One

Thanks for info. Must have messed something up in package manager. It's getting exhausting updating on GH which I then duplicate in the package manager so definitely need a better work flow. :-)

**Comment by Hypexed** [comment]
This should be good to go now.

**Comment by cfillion** [comment]
Replaced by #1099.

**Pull request closed without merging**
