### PR TITLE
Create ReaNoir

### PR DESCRIPTION
**Pull request by amagalma**
Utility to color Tracks/Items/Takes

### CODE REVIEW

**Review by cfillion — CHANGES_REQUESTED** [review]
1. Please name the file "Various/amagalma_ReaNoir.lua", not just "Various/ReaNoir"
2. Ensure every lines of the `@about` tag are indented with at least one space (or tabs). Currently the first line (`# Track/Item/Take coloring utility`) is the only indented one.

You can modify the file in this Pull Request from this URL without having to create a new one: https://github.com/amagalma/ReaScripts/edit/patch-2/Various/ReaNoir.

**Comment by X-Raym** [comment]
Maybe spacemantree_amalgama_ for the prefix ?
Also, you can add keywords like Reanoir color managrt so it is easier to discover in action list :P

**Comment by amagalma** [comment]
Hope all is good now! :)

**Comment by X-Raym** [comment]
@amalgama
Close ! But you missed the .lua file extension :P

**Comment by amagalma** [comment]
Oh god!.. :S... rocket science!...

**Review by cfillion — APPROVED** [review]

**Comment by cfillion** [comment]
The indentation of the about tag was still a little off (the first line had two spaces while the others had only one – it must be consistent). I've fixed it for you in the commit above. 😸 

Also note that you don't need to repeat the "amagalma_" prefix in the description tag, it just clutters the package list which has a searchable Author column anyway. We put that in the file name so it can be seen and searched in the Action List.

**Pull request merged**
