### PR TITLE
Lokasenna Lua GUI Framework: Reapack compatibility

### PR DESCRIPTION
**Pull request by jalovatt**
Yay, I'm finally getting around to a ReaPack release so people don't have to distribute the library themselves.

@cfillion, would you mind having a look to make sure this will install the way I'm expecting? There are two metapackages in the Development folder, each of which is intended to provide their respective subfolders, maintaining the folder structure on the user's drive (i.e. _Reaper/Scripts/ReaTeam/Development/Lokasenna_GUI/Library_)

### CODE REVIEW

**Comment by jalovatt** [comment]
I see that the build failed. Adding NoIndex tags as needed...

**Comment by jalovatt** [comment]
Not sure how to resolve the Duplicate File errors I'm getting. :/

**Comment by cfillion** [comment]
Some files were matched by both `*.*` and `**/*.*` (`**` enables recursive search) causing them to be listed twice.

I also renamed the packages to `Lokasenna_GUI library v2.lua` and `Lokasenna_GUI library v2 (developer tools).lua` (both internal package ID and displayed name, matching the thread title). I can revert this if you prefer the old name (I think "package" shouldn't be in the package ID/name though).

Lokasenna's GUI library for Lua

https://cfillion.ca/files/.lokasenna-test.xml

**Comment by jalovatt** [comment]
That looks fine.

I did some Googling about Ruby's file-matching but couldn't figure out the proper wildcard terms. Thanks.

**Pull request merged**
