### PR TITLE
Release MIDI looping step velocity v1.0

### PR DESCRIPTION
**Pull request by mpasserini**
Initial commit of mpasserini_MIDI_looping_step_velocity.eel

### CODE REVIEW

**Comment by X-Raym** [comment]
@mpasserini
Why not having your own repo if you are already on github ? https://github.com/mpasserini/REAPER-ReaScripts/tree/main/MIDI/MIDI_looping_step_velocity

you can fork this one if you want to save a bit of time rather than setting it manually: https://github.com/cfillion/reapack-repository-template

**Comment by mpasserini** [comment]
Hi @X-Raym , thanks!
 I tried creating the repo, do you think it's OK? https://github.com/mpasserini/REAPER-ReaScripts

It fails on deploy:

Run git push
remote: Permission to mpasserini/REAPER-ReaScripts.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/mpasserini/REAPER-ReaScripts/': The requested URL returned error: 403
Error: Process completed with exit code 128.

Do I need to configure some special permissions?
Shall we cancel this merge request?

**Comment by X-Raym** [comment]
@mpasserini Hmm never seen this error, looks like permission issue indeed. @cfillion maybe?

We will close this when you will be set up

**Comment by cfillion** [comment]
Is "Workflow permissions" set to "Read and write" under Settings > Actions?

Personally I wouldn't recommend maintaining your own repository unless you plan to actively make hundreds of scripts. Using ReaTeam makes them available out of the box to all users without having to manually import a third-party repository. Plus each contributions are checked for correctness and best packaging practices before release.

EDIT: I think this is the first EEL ReaImGui script (at least that I'm aware of)!

**Comment by X-Raym** [comment]
@cfillion to all users... only if they have checked the 'install new packages' options :P

@mpasserini
More than quantity, the advantage of having your own repo is that you can release when you want. So it can also be useful if you have a script you want to update often. As this script is a script with GUI which has some feedbacks on the forum already, I thought that might be the case.
Anyway, it is up to you to decide, we will help in any of these directions.

**Comment by cfillion** [comment]
> @cfillion to all users... only if they have checked the 'install new packages' options :P

I meant that packages on ReaTeam are made available in the package browser of all users out of the box. Deciding to install or not is of course up to the user.

**Comment by mpasserini** [comment]
Hi, for me one way of the other is the same really... 

As X-Raym says though, it might be easier to fix bugs with the automatic workflow. I'm not sure whether I'll develop a lot of plugins for the future.

Anyways, to get back to the "Actions" problem, I configured:

* Allow all actions and reusable workflows
* Read and write permissions

Now I get a different error:

Error: .github#L1
actions/checkout@v2 and ruby/setup-ruby@v1 are not allowed to be used in mpasserini/REAPER-ReaScripts. Actions in this workflow must be: within a repository owned by mpasserini.

Any idea?

**Comment by cfillion** [comment]
Is "Allow actions created by GitHub" and "Allow actions by Marketplace verified creators" enabled in the same settings page? I think that used to be the case by default it could have changed recently.

Releasing on ReaTeam does mean waiting a little bit for a human (usually me) to check and merge the PRs.

**Comment by mpasserini** [comment]
>Is "Allow actions created by GitHub" and "Allow actions by Marketplace verified creators" enabled in the same settings page? I think that used to be the case by default it could have changed recently.

No I can't find that option :(

**Comment by cfillion** [comment]
Screen Shot 2023-03-01 at 11 02 01

(with your username instead of mine)

**Comment by mpasserini** [comment]
Thanks! I did what you adviced and it seems to have worked.  Is it ok on your side?

**Comment by X-Raym** [comment]
@mpasserini it's good!

Add the index.xml raw URL in the readme for convenience for the user with minimal Reapack instructions or link.

```https://github.com/mpasserini/REAPER-ReaScripts/raw/master/index.xml```

I can close the ticket:) Thx for your contribution to scripting :P

**Pull request closed without merging**
