### PR TITLE
Update beaunus_clip_splicer 2.1

### PR DESCRIPTION
**Pull request by beaunus**
Christian,

I have made some improvements to beaunus_clip_splicer. Again, I didn't do the proper merging on my end, but I think that I have fixed it so that it should be simple to merge for you. I apologize for any inconvenience. Please let me know if I should do something else to make this code ready for your repository.

Thank you.
Beau

### CODE REVIEW

**Comment by cfillion** [comment]
Build is failing with the following errors:

```
1) Various/beaunus_clip_splicer/__init__.py failed:
  missing tag 'version'

2) Various/beaunus_clip_splicer/beaunus_clip_splicer_tools.py failed:
  missing tag 'version'

Finished checks for 395 packages with 2 failures
```

Add `@noindex` in a comment at the top of beaunus_clip_splicer_tools.py to make reapack-index skip the file.

Is \_\_init\_\_.py required? It's not listed in the provides tag thus will not be installed on the user's computer.

**Comment by beaunus** [comment]
Christian, 

Thank you for your help with this.

I'll briefly tell you my intention with this package and you can let me know if you think it's worth including in this repo.

`beaunus_clip_splicer` is a tool for creating REAPER sessions from a formal JSON document. It is a good way to automatically generate a session if you have a JSON document that specifies its _rough layout_.

However, generating the JSON files is part of any project that uses `beaunus_clip_splicer`. I created `beaunus_clip_splicer_tools.py` to abstract some of the nuts-and-bolts functionality that I was constantly re-writing for similar projects.

The reason that `__init__.py` is included is so that this tool can be imported into another python script. For example, this is what the import looks like when I write a JSON generator:

```python
import beaunus_clip_splicer_tools
```

In order to make the above line work, `beaunus_clip_splicer_tools` needs to be in a Python package. Thus, it needs to be in a folder with an `__init__.py` file.

This being said, do you think that your repository is the right place for this tool? If so, I will resolve the issues that you mentioned and update the pull request.

Thank you for your consideration.
Beau

**Comment by cfillion** [comment]
If I'm understanding right, Import_clip_splicer_specification_json.py and beaunus_clip_splicer_tools.py are two separate half of the project, the later only to be used by external python scripts not included in this repository?

I'm not familiar with Python and how it looks for files to import, but if you think having beaunus_clip_splicer_tools.py put in REAPER's resource directory makes it easier to install and use, I think it's OK to include it. Otherwise perhaps it should go in the Python Package Index?

**Comment by beaunus** [comment]
Hi Christian,

Yes. Your first paragraph is correct.

I will look into using PyPI. If I decide to pull request again, I will address the "tag" issue that you explained above. Thank you for your help. I'll close this PR and open a new one in the future.

**Pull request closed without merging**
