### PR TITLE
FnA trying to get connected

### PR DESCRIPTION
**Pull request by fnaFnaFnAFNA**
trying to get connected after failing in May / June.

### CODE REVIEW

**Comment by cfillion** [comment]
Thanks for submitting these scripts! They are good for release as-is, but I have a few suggestions:

First, please move the scripts into one of the existing folders in order to keep the categories consistent. "item" should be "Item Editing". Also the script "FnA_Force toggle off (item grouping).lua" in "various" is identical to the one in "item". 😉 

I notice you are using the old-style header from before ReaPack. Many of these tags are unused or were replaced. I suggest using this for best results:

```lua
-- Description: Force toggle OFF (item grouping)
-- Version: 1.0
-- Author: FnA
-- Changelog: Initial release
-- Link: Forum Thread (somewhat indirectly) http://forum.cockos.com/showthread.php?t=191368
-- About:
--   Optionally write a description or documentation of what this script does, what
--   problems it solves and how to use it in this *indented* block of Markdown text.

your code here
```

You might also be interested into releasing these scripts as two packages since they are likely to be used together. Examples of such multi-script packages are "Toggle take FX bypass for selected items" and Lokasenna's "Radial Menu". (Ignore the following paragraph if you aren't interested.)

Additionally, since both the ON and OFF scripts are pretty similar, you can use this trick to have both scripts released as one package in ReaPack but *also* as one file to upload in this repository. An update to the OFF script would automatically apply to its sibling ON script:

**Item Editing/FnA_Force toggle (item grouping).lua**

```lua
-- Description: Force toggle ON/OFF (item grouping)
-- Version: 1.0
-- Author: FnA
-- Changelog: Initial release
-- Link: Forum Thread (somewhat indirectly) http://forum.cockos.com/showthread.php?t=191368
-- About:
--   Optionally write a description or documentation of what this script does, what
--   problems it solves and how to use it in this *indented* block of Markdown text.
-- MetaPackage: true
-- Provides:
--   [main] . > FnA_Force toggle ON (item grouping).lua
--   [main] . > FnA_Force toggle OFF (item grouping).lua

local filename = ({reaper.get_action_context()})[2]:match("([^/\\_]+).lua$")
local isON = filename:match("ON")

"code here that toggles the action on or off depending on `isON`"
```

If you want, the same can be done with Unselect first & last selected item.

**Comment by fnaFnaFnAFNA** [comment]
hope it is all here (for now)
Thanks for the help.

**Comment by fnaFnaFnAFNA** [comment]
woops.
don't press Close and Comment!

**Comment by cfillion** [comment]
👍 

Screenshot

**Comment by cfillion** [comment]
I tweaked the description tags a tiny bit to have all script names start with an uppercase letter as in the Action List and remove the unnecessary ".lua".

**Pull request merged**
