### PR TITLE
Add tompad_FX_chain_AB.lua

### PR DESCRIPTION
**Pull request by tompad2**
I try to upload it here - ReaPacksite gave error.

### CODE REVIEW

**Comment by X-Raym** [comment]
@tompad2 Hi, the script miss a file_exists check beforr looking for ultraschall API file.

Please implement code snippet from there:
https://github.com/Ultraschall/ultraschall-lua-api-for-reaper

**Comment by cfillion** [comment]
>  ReaPacksite gave error.

What was the error message?

**Comment by X-Raym** [comment]
@tompad2 also, can you put this script in the FX folder category? Thx!

**Comment by X-Raym** [comment]
@tompad2 oh dont worry took care of this. I case it can be merged unless @cfillion has other concerns.

**Comment by tompad2** [comment]
> cfillion

The error was when uploading - the wheel turned some seconds
and then a red sign with a close button turned up.

**Comment by tompad2** [comment]
> @tompad2 oh dont worry took care of this. I case it can be merged unless @cfillion has other concerns.

Thanks X-Raym!

**Comment by tompad2** [comment]
Do I need to do something more? Or is just to sit down and relax and wait? ;-)

**Pull request merged**
