### PR TITLE
Added two new region scripts

### PR DESCRIPTION
**Pull request by Landeplage**
I use these scripts daily. Great for game audio SFX exporting.

### CODE REVIEW

**Comment by Buy-One** [comment]
@Landeplage 

Hey

You seem to have forgotten to add `Provides: [main] .` tag.

**Comment by Landeplage** [comment]
@Buy-One Trying to find documentation on how to use that tag, but not finding any. The two scripts are independent. Do they still need the `Provides` tag?

Edit: Found documentation, but still a bit unclear. Should each PR only consist of a single file if they are independent?
https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation#provides

**Comment by Landeplage** [comment]
@Buy-One Nevermind - was able to figure it out. Thanks for the tip about the Provides tag.

**Comment by cfillion** [comment]
A provides tag is not necessary. The issue was caused by the empty `changelog` tag. Will merge this later.

I recommend using the form at https://reapack.com/upload to automatically generate the metadata and submit the pull requests.

**Comment by Buy-One** [comment]
> A provides tag is not necessary

Does this mean that without explicit Provides tag the script is always installed in the Main section and only if other sections are involved it's necessary?

**Comment by cfillion** [comment]
Yes. The default is to register the script in the Action List's main section (or in the MIDI Editor if it's the folder with the same name).

**Comment by cfillion** [comment]
Looked more closely into it before merging, these two scripts appear to be variations on your existing "Create single region from selected items (get name and color from folder track)" script.

Additional actions should be added to the existing package instead of submitted separately. This can be done using the GUI at https://reapack.com/upload:

1. Type "Create single region from selected items" in the name field and click on your package to load it in the editor
2. Bump the version number of the package
3. Drag/drop both new script files over the "Add file" button
4. For each of those two files, click on the "Action List" drop-down menu and enable registering them as actions in the Main section

**Comment by Landeplage** [comment]
@cfillion Done.

Is there any meaningful distinction between the "Package file" and the "Hosted files"?
https://i.imgur.com/8cookfl.png

**Comment by cfillion** [comment]
The only difference is the "package file" contains the metadata information, which the other files don't have (except for a "noindex" tag).

**Pull request closed without merging**
