### PR TITLE
Added Claudiohbsantos Repo

### PR DESCRIPTION
**Pull request by Claudiohbsantos**

### CODE REVIEW

**Comment by X-Raym** [comment]
@Claudiohbsantos Excellent ! But you didn't put it in the alphabetical order ! Can you correct ?

**Comment by Claudiohbsantos** [comment]
@X-Raym Oh, didn't realize they were in alphabetical order. I believe I corrected the commit, let me know if I didn't

**Comment by cfillion** [comment]
I've added it on the list at https://reapack.com/repos. But I doubt you intended for the repository to be named "_o-amend_" (according to the index)?

Claudiohbsantos/Claudiohbsantos-Scripts@82c3f2f7bbc312e4e3ac718f372eca2191dedf1e

**Comment by Claudiohbsantos** [comment]
Ops, I must have made a mess with the index at some point and didn't notice because in the extension it still showed the right name. Once imported does it not update name changes?

Anyway, thanks for pointing it out. It should be fixed now

(Screenshot of what I saw in the extension)

screenclip

**Comment by cfillion** [comment]
Thanks! The website will auto-update with correct name in a few minutes.

> Once imported does it not update name changes?

You're correct, once the repository imported the name becomes read-only.

**Pull request merged**
