### PR TITLE
Release Switch unlocked items only to next take (grouped items with a locked item in their group do not switch) v1.00

### PR DESCRIPTION
**Pull request by amagalma**

### CODE REVIEW

**Comment by cfillion** [comment]
The "previous take" action is almost identical and has little purpose in being made available separately. Shouldn't it be bundled together with the "next take" action in the same ReaPack package?

**Comment by amagalma** [comment]
No problem.. But I have forgotten how to do it :S

**Comment by cfillion** [comment]
Method 1 (two script files + one package file): licecap

Method 2 (reusing the same script file, detecting next vs previous at runtime via the filename): https://i.imgur.com/qcVfsoy.gif

**Comment by amagalma** [comment]
I did it manually...

Will that work?
```lua
-- @description Switch unlocked items only to previous or next take bundle
-- @author amagalma
-- @version 1.00
-- @metapackage
-- @provides
--   [main] . > Switch unlocked items only to previous take (grouped items with a locked item in their group do not switch)
--   [main] . > Switch unlocked items only to next take (grouped items with a locked item in their group do not switch)
-- @about Like native Take: Switch items to previous/next take, but without switching takes for items that are locked or belong to a group with a locked item

local name = ({reaper.get_action_context()})[2]:match("([^/\\_]+).lua$")
local mode = name:match('previous') and -1 or 1


local item_cnt = reaper.CountMediaItems( 0 )
local sel_item_cnt = reaper.CountSelectedMediaItems( 0 )
if item_cnt == 0 or sel_item_cnt == 0 then return reaper.defer(function() end) end

-- Get groups with locked items
local locked_groups = {}
for i = 0, item_cnt-1 do
	local item = reaper.GetMediaItem( 0, i )
	local group = reaper.GetMediaItemInfo_Value( item, "I_GROUPID" )
	if group ~= 0 then
		if reaper.GetMediaItemInfo_Value( item, "C_LOCK" ) & 1 == 1 then
			locked_groups[group] = true
		end
	end
end



-- Get items to unselect
local items = {}
local count = 0

for i = 0, sel_item_cnt-1 do
	local item = reaper.GetSelectedMediaItem( 0, i )
	local group = reaper.GetMediaItemInfo_Value( item, "I_GROUPID" )
	if reaper.GetMediaItemInfo_Value( item, "C_LOCK" ) & 1 == 1 or locked_groups[group] then
		count = count + 1
		items[count] = item
	end
end

if count == sel_item_cnt then return reaper.defer(function() end) end


reaper.PreventUIRefresh( 1 )

-- Unselect
for i = 1, count do
	reaper.SetMediaItemSelected( items[i], false )
end

local name
if mode == -1 then
	reaper.Main_OnCommand(40126, 0) -- Switch items to previous take
	name = "previous"
else
	reaper.Main_OnCommand(40125, 0) -- Switch items to next take
	name = "next"
end

-- Restore selection
for i = 1, count do
	reaper.SetMediaItemSelected( items[i], true )
end


reaper.PreventUIRefresh( -1 )
reaper.UpdateArrange()


reaper.Undo_OnStateChange( "Switch unlocked items only to .. " .. name .. " take" )
```

**Comment by cfillion** [comment]
All that's missing is `.lua` and `amagalma_` at the end and start of the filenames in `@provides`. Otherwise, looks all good! 👍

**Comment by amagalma** [comment]
Good! :) I ll add them , close these pull requests and do a new one with the bundle.

**Comment by cfillion** [comment]
```lua
reaper.Undo_OnStateChange( "Switch unlocked items only to .. " .. name .. " take" )
```

...should probably be:

```lua
reaper.Undo_OnStateChange( name )
```

...otherwise the undo point will read "Switch unlocked items only to .. *Switch unlocked items only to previous take (grouped items with a locked item in their group do not switch)* take".

**Comment by amagalma** [comment]
I have another instance of `local name` before `if mode == -1 then` . But I could change it to `local undo` just to be safe

**Comment by cfillion** [comment]
Ah right, missed that!

**Comment by amagalma** [comment]
No problem! :) Thank you for the help! I just did a pull request for the bundle

**Pull request closed without merging**
