### PR TITLE
Release Toggle bypass FX on selected track v1.0

### PR DESCRIPTION
**Pull request by Tagirijus**

### CODE REVIEW

**Comment by X-Raym** [comment]
@Tagirijus in reaper terminology, both instrument and non instrument are called FX. the script name should reflect it doesnt bypass instrument.

**Comment by Tagirijus** [comment]
Thanks for your comment on this. Do you think _"bypass effects"_ instead of _"bypass FX"_ would be good? Or do you have any other cool naming ideas?

**Comment by X-Raym** [comment]
The more explicit is cool like

Toggle bypass non-instrument FX on selected tracks

This is good :P

**Comment by Tagirijus** [comment]
Ok, I changed it locally ... but how can I change this with the Package editor website of ReaPack? /-:

**Comment by X-Raym** [comment]
dont use reapack website. Check this above comment box :

Add more commits by pushing to the [reapack.com_upload-1644398133596](https://github.com/Tagirijus/ReaScripts/tree/reapack.com_upload-1644398133596) branch on [Tagirijus/ReaScripts](https://github.com/Tagirijus/ReaScripts).

**Comment by X-Raym** [comment]
on other words, go to https://github.com/Tagirijus/ReaScripts/tree/reapack.com_upload-1644398133596 and do your file edit from there.

**Comment by Tagirijus** [comment]
Thanks so much for the help. I just did so. Hopefully it will work as intended! (=

**Comment by X-Raym** [comment]
@Tagirijus Looks good to me ! thx for your contribution ! 🙏

**Pull request merged**
